# Generated by Django 5.0.1 on 2024-02-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_restaurant_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
