# Generated by Django 5.0.1 on 2024-02-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_employee_username_alter_employee_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='items',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
