# Generated by Django 5.0.1 on 2024-02-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_menu_desc_menu_image_alter_menu_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurantId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
